apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: j6crypto-engine
    name: j6crypto-engine
    namespace: j6crypto
  spec:
    ports:
    - name: http
      port: 8082
      protocol: TCP
      targetPort: http
    selector:
      app: j6crypto-engine
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: j6crypto-engine
    namespace: j6crypto
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: j6crypto-engine
    strategy:
      type: Recreate 
    template:
      metadata:
        labels:
          app: j6crypto-engine
      spec:
        containers:    
        - env:
            - name: server.port
              value: "8082"
            - name: spring.cloud.zookeeper.connect-string
              value: "zookeeper:2181"
            - name: spring.kafka.bootstrap-servers
              value: "kafka.j6crypto.svc.cluster.local:9092"
            - name:   spring.kafka.producer.bootstrap-servers
              value: "kafka.j6crypto.svc.cluster.local:9092"
            - name:   spring.kafka.consumer.bootstrap-servers
              value: "kafka.j6crypto.svc.cluster.local:9092"
#            - name: spring.kafka.properties.security.protocol
#              value: "SASL_PLAINTEXT"
#            - name: spring.kafka.properties.sasl.jaas.config
#              value: "org.apache.kafka.common.security.plain.PlainLoginModule   required username='user'   password='bitnami'   serviceName='Kafka';"
##            - name: spring.kafka.ssl.allow.everyone.if.no.acl.found
##              value: 'true'
##            - name: spring.kafka.jaas.enabled
##              value: 'false'
##            - name: spring.kafka.sasl.allow.everyone.if.no.acl.found
##              value: 'true'
#            - name: spring.kafka.properties.sasl.mechanism
#              value: 'PLAIN'
#          spring.kafka.bootstrap-servers=PLAINTEXT://127.0.0.1:9092
          name: j6crypto-engine
          ports:
          - containerPort: 8082
            name: http
          resources:
            requests:
              memory: 256Mi        
          image: jimmy6au/j6crypto-engine:0.0.3-SNAPSHOT
          imagePullPolicy: Always
kind: List
