apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: kafka
    name: kafka
    namespace: j6crypto
  spec:
    ports:
    - name: client
      port: 9093
      protocol: TCP
      targetPort: client
    - name: external
      port: 9092
      protocol: TCP
      targetPort: external
    selector:
      app: kafka   
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: kafka
    namespace: j6crypto
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: kafka
    strategy:
      type: Recreate 
    template:
      metadata:
        labels:
          app: kafka     
      spec:
        containers:    
        - env:
          - name: ALLOW_PLAINTEXT_LISTENER
            value: 'yes'
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: 'zookeeper:2181'
          - name: KAFKA_CFG_LISTENERS
            value: 'CLIENT://:9093,EXTERNAL://:9092'
          - name: KAFKA_CFG_ADVERTISED_LISTENERS
            value: 'CLIENT://localhost:9093,EXTERNAL://kafka.j6crypto.svc.cluster.local:9092'
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: 'CLIENT'
          - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
            value: 'CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT'
          - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
            value: 'true'
          name: kafka
          ports:
          - containerPort: 9092
            name: external
          - containerPort: 9093
            name: client
          resources:
            requests:
              memory: 256Mi        
          image: bitnami/kafka:2.8.0-debian-10-r55
          imagePullPolicy: Always    
kind: List
