apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: public-ingress
  namespace: j6crypto
spec:
  rules:
    - host: "*.123432323.cn-hongkong.alicontainer.com"
      http:
        paths:
          - path: /
            backend:
              serviceName: j6crypto-gateway
              servicePort: 8080