apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: zookeeper
    name: zookeeper
    namespace: j6crypto
  spec:
    ports:
      - port: 2888
        name: server
      - port: 3888
        name: leader-election
      - port: 2181
        name: client
    selector:
      app: zookeeper   
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: zookeeper
    namespace: j6crypto
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: zookeeper
    strategy:
      type: Recreate    
    template:
      metadata:
        labels:
          app: zookeeper     
      spec:
        containers:    
        - env:
          - name: ALLOW_ANONYMOUS_LOGIN
            value: 'yes'
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: server
            - containerPort: 3888
              name: leader-election
          resources:
            requests:
              memory: 256Mi
          name: zookeeper
          image: bitnami/zookeeper:3.6.3-debian-10-r44
          imagePullPolicy: Always    
kind: List